attributes:
  metadata:
    group: 'storage'
    restrictions:
      - condition: "cluster:status == 'operational'"
        action: "none"
        message: |
          INFO: HOT PLUG is fully supported.

  san_ip:
    value: ''
    label: 'Management IP'
    description: 'Management IP of Unity'
    weight: 25
    type: 'text'

  san_login:
    value: ''
    label: 'Username'
    description: 'User account for accessing Unity.'
    weight: 30
    type: 'text'

  san_password:
    value: ''
    label: 'Password'
    description: 'Password for accessing Unity.'
    weight: 35
    type: 'password'

  storage_protocol:
    value: 'iSCSI'
    values:
        - data: 'iSCSI'
          label: 'iSCSI'
          description: ''
        - data: 'FC'
          label: 'FC'
          description: ''
    label: 'Storage Protocol'
    description: 'Protocol for transferring data.'
    weight: 40
    type: 'radio'

  manage_all_pool:
    value: 'Yes'
    label: 'Manange all pools'
    description: 'Whether to manage all pools.'
    weight: 45
    type: 'select'
    values:
      - data: 'Yes'
        label: 'Yes'
      - data: 'No'
        label: 'No'

  storage_pool_names:
    value: ''
    label: 'Storage pool(s)'
    description: 'Comma separated pool name(s) to be managed.'
    weight: 50
    type: 'text'
    restrictions:
      - condition: "settings:cinder-unity.manage_all_pool.value == 'Yes'"
        action: 'hide'

  volume_driver:
    value: 'cinder.volume.drivers.emc.emc_unity.EMCUnityDriver'
    label: 'volume_driver'
    description: >
      Unity driver name(Do *NOT* change it unless you know what you are doing).
    weight: 55
    type: 'text'

  volume_backend_name:
    value: 'emc-unity'
    label: 'Backend name for this configuration'
    description: 'Backend name for this configuration.'
    weight: 60
    type: 'text'

  iscsi_use_multipath:
    value: true
    label: 'Use multipath connection of volume'
    description: 'Multipath for Nova and Unity'
    weight: 70
    type: 'checkbox'

  max_over_subscription_ratio:
    value: '20.0'
    label: 'Max Over Subscription Ratio'
    description: >
      Float representation of the over subscription ratio
      when thin provisioning is involved. Default ratio is
      20.0, meaning provisioned capacity can be 20 times of
      the total physical capacity.
    weight: 75
    type: 'text'
