#!/bin/bash

# Add here any the actions which are required before plugin build
# like packages building, packages downloading from mirrors and so on.
# The script should return 0 if there were no errors.
echo "Starting Unity fuel plugin deployment..."
echo "this is a test"
echo "this is a test2"
echo "this is a test3"

